routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TopikController;
use App\Http\Controllers\KomentarController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('kategori', KategoriController::class)->middleware('auth');

Route::resource('profil', ProfilController::class)->middleware('auth');

Route::resource('topik', TopikController::class)->middleware('auth');

Route::resource('komentar', KomentarController::class)->middleware('auth');

Route::get('tinymce', function(){
    return view('tinymce.index');
});

app/Models/Topik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use App\Models\User;
use App\Models\Kategori;
use App\Models\Komentar;

class Topik extends Model
{
    use HasFactory;
    protected $table = "topik";

    protected $fillable = ['judul', 'pertanyaan', 'gambar', 'kategori_id', 'user_id'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function kategori(){
        return $this->belongsTo(Kategori::class);
    }

    public function komentar(){
        return $this->hasMany(Komentar::class);
    }


}

app/Http/Controllers/TopikController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\Kategori;
use App\Models\Topik;
use App\Models\Komentar;

use Image;


class TopikController extends Controller
{
    public function index(){
        $data = Topik::all();
        return view('topik.index', compact('data'));
    }
    //
    public function create(){
        $kategori = Kategori::all();
        return view('topik.new', compact('kategori'));
    }

    public function store(Request $request)
    {        
        $request->validate([
            'judul' => ['required', 'max:255'],
            'pertanyaan' => ['required'],
            'gambar' => ['required'],
            'kategori' => ['required']
        ]);

        $image = $request->file('gambar');
        $filename= date('YmdHi').$image->getClientOriginalName();
        $thumbImage = Image::make($image->getRealPath());
        
        $height = $thumbImage->height();
        $width = $thumbImage->width();

        if ($height < $width){
            $thumbImage->resize(($width/($height/200)), 200);
        } else {
            $thumbImage->resize(200, ($height/($width/200)));
        }

        $thumbPath = public_path() . '/image/' . $filename;
        $thumbImage->crop(200, 200);
        $thumbImage = Image::make($thumbImage)->save($thumbPath);

        //$file-> move(public_path('image'), $filename);
        //print_r($request->all());
        //print_r($file);
        $user = Auth::user();
        
        Topik::create([
            'judul' => $request->judul,
            'pertanyaan' => $request->pertanyaan,
            'gambar' => $filename,
            'kategori_id' => $request->kategori,
            'user_id' => $user->id
        ]);

        return redirect('topik')->with('success', 'Topik berhasil ditambahkan ...');
    }

    public function edit($id)
    {
        $topik = Topik::find($id);
        $kategori = Kategori::all();
        return view('topik.edit', compact('topik', 'kategori'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => ['required', 'max:255'],
            'pertanyaan' => ['required'],
            'kategori' => ['required']
        ]);

        Topik::find($id)->update([
            'judul' => $request->judul,
            'pertanyaan' => $request->pertanyaan,
            'kategori_id' => $request->kategori,
        ]);

        return redirect('topik')->with('success', 'Topik berhasil diupdate ...');
    }

    public function show($id){
        $komentar = Komentar::where('topik_id', '=', $id)->get();;
        $topik = Topik::find($id);
        return view('topik.show', compact('topik', 'komentar'));
    }

    public function destroy($id)
    {
        Topik::find($id)->delete();
        return redirect()->back()->with('success', 'Topik Berhasil Terhapus !!');
    }

}

resources/views/topik/edit.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Edit Topik</h1>
            </section>
            <section class="mdc-card__supporting-text">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
                        <form action={{ route('topik.update', $topik->id) }} method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="template-demo">
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="umur" class="mdc-text-field__input" name="judul" value="{{$topik->judul}}"">
                                        <label class="mdc-floating-label" for="my-text-field">Judul</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('judul')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="bio" class="mdc-text-field__input" name="pertanyaan" value="{{$topik->pertanyaan}}"">
                                        <label class="mdc-floating-label" for="my-text-field">Pertanyaan</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('topik')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <br>
                                    <select name="kategori">
                                    @forelse ($kategori as $kat)
                                        <option value="{{$kat->id}}">{{$kat->nama}}</option>
                                    @empty
                                        <option value="null">Belum ada kategori</option>
                                    @endforelse
                                    </select><br>
                                    <label for="kategori">Kategori</label>
                                </div>
                                

                                <button type="submit" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                                    Simpan
                                </button>
                                <a href={{ route('topik.index') }}
                                    class="mdc-button mdc-button--raised secondary-filled-button"
                                    data-mdc-auto-init="MDCRipple">
                                    Kembali
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/topik/index.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Topik</h1>
                <hr>
                <a href={{ route('topik.create') }} class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                    Tambah Topik
                </a>
            </section>
            <div>
                <table class="table table-hoverable">
                    <thead>
                        <tr>
                            <th width="15%" class="text-left">No</th>
                            <th width="60%" class="text-left">Judul</th>
                            <th width="25%" class="text-left"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $no = 0;
                            $public_folder = public_path();
                        @endphp
                        @forelse ($data as $row)
                            @php
                                $no = $no + 1;
                            @endphp
                            <tr>
                                <td class="text-left">{{ $no }}</td>
                                <td class="text-left"><a href="{{ route('topik.show', $row->id)}}">{{ $row->judul }}</a></td>
                                <td class="text-left">
                                    <div class="d-flex">
                                        @if ($row->user->id == Auth::user()->id)
                                        <a class="mdc-button mdc-button--raised" href={{ route('topik.edit', $row->id) }}
                                            data-mdc-auto-init="MDCRipple">Edit</a>
                                        <form class="pl-1" action={{ route('topik.destroy', $row->id) }}
                                            method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $row->id }}">
                                            <button class="mdc-button mdc-button--raised secondary-filled-button"
                                                type="submit" data-mdc-auto-init="MDCRipple">Hapus</button>
                                        </form>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="text-left"><img src="{{ asset('image/'.$row->gambar)}}" height="100"></td>
                                <td class="text-left">{{ $row->pertanyaan }}</td>
                                @php
                                @endphp
                                <td class="text-left"></td> 
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center">Data kosong</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/topik/new.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Buat Profile</h1>
            </section>
            <section class="mdc-card__supporting-text">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
                        <form action={{ route('topik.store') }} method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="template-demo">
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="umur" class="mdc-text-field__input" name="judul">
                                        <label class="mdc-floating-label" for="my-text-field">Judul</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('umur')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="bio" class="mdc-text-field__input" name="pertanyaan">
                                        <label class="mdc-floating-label" for="my-text-field">Pertanyaan</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('bio')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <br>
                                    <div class="image">
                                        <input type="file" class="form-control" required name="gambar"><br>
                                        <label for="gambar">Masukkan Gambar</label>
                                    </div>
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <br>
                                    <select name="kategori">
                                    @forelse ($kategori as $kat)
                                        <option value="{{$kat->id}}">{{$kat->nama}}</option>
                                    @empty
                                        <option value="null">Belum ada kategori</option>
                                    @endforelse
                                    </select><br>
                                    <label for="kategori">Kategori</label>
                                </div>
                                

                                <button type="submit" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                                    Simpan
                                </button>
                                <a href={{ route('topik.index') }}
                                    class="mdc-button mdc-button--raised secondary-filled-button"
                                    data-mdc-auto-init="MDCRipple">
                                    Kembali
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/topik/show.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Kategori {{ $topik->kategori->nama }}</h1>
                <hr>
                Topik {{ $topik->judul}}
            </section>
            <div>
                <table class="table table-hoverable">
                    <thead>
                        <tr>
                            <th width="60%" class="text-left">Thread</th>
                            <th width="25%" class="text-left"></th>
                            <th width="15%" class="text-left"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan=2 class="text-left">{{ $topik->pertanyaan }}</td>
                            <td class="text-left"><img src="{{ asset('image/'.$topik->gambar)}}" height="100"></td>
                        </tr>
                        
                        @forelse ($komentar as $row)
                            <tr>
                                <td class="text-left">
                                    {{ $row->komentar }}
                                </td>
                                <td class="text-left">
                                    Komentar oleh <br> {{ $row->user->name}}
                                </td>
                                <td class="text-left">
                                @if ($row->user->id == Auth::user()->id)
                                        <a class="mdc-button mdc-button--raised" href={{ route('komentar.edit', $row->id) }}
                                            data-mdc-auto-init="MDCRipple">Edit</a>
                                        <form class="pl-1" action={{ route('komentar.destroy', $row->id) }}
                                            method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $row->id }}">
                                            <button onclick="deleteConfirm('delele-product-form-39')" class="mdc-button mdc-button--raised secondary-filled-button"
                                                type="submit" data-mdc-auto-init="MDCRipple">Hapus</button>
                                        </form>
                                @endif
                                </td>
                            </tr>
                        @empty
                            
                        @endforelse
                            </td>
                        </tr>
                        <tr>
                            @auth
                            <td colspan=3>
                            <form method="POST" action="{{route('komentar.store')}}">
                                @csrf
                                <label class="mdc-floating-label" for="my-text-field">Tambah Komentar</label>
                                <input type="hidden" name="topik_id" value={{ $topik->id }}>
                                <input type=text name="komentar" class="mdc-text-field__input">
                                <button type="submit" class="mdc-button mdc-button--raised">Tambah</button>
                                <button type="reset" class="mdc-button mdc-button--raised secondary-filled-button">Reset</button>
                            </form>
                            </td>
                            @endauth
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection