routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TopikController;
use App\Http\Controllers\KomentarController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('kategori', KategoriController::class)->middleware('auth');

Route::resource('profil', ProfilController::class)->middleware('auth');

Route::resource('topik', TopikController::class)->middleware('auth');

Route::resource('komentar', KomentarController::class)->middleware('auth');

Route::get('tinymce', function(){
    return view('tinymce.index');
});

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\profile;

class ProfilController extends Controller
{
    //
    public function index(){
        $user = Auth::user();

        //$user = User::where('email', '=', Input::get('email'))->first();
        $profil = profile::where('user_id', '=', $user->id)->first();

        if ($profil === null){
            return view('profil.new');
        }


        return view('profil.index', compact('profil'));
    }

    public function create(){
        return view('profil.new');
    }

    public function edit($id){
        $profil = profile::where('user_id', '=', $id)->first();
        return view('profil.edit', compact('profil'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'umur' => ['required', 'max:999', 'numeric'],
            'bio' => ['required'],
            'alamat' => ['required']
        ]);
        profile::find($id)->update([
            'umur' => $request->umur,
            'bio' => $request->bio,
            'alamat' => $request->alamat
        ]);

        return redirect('profil')->with('success', 'Profil berhasil diupdate ...');
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        $request->validate([
            'umur' => ['required', 'max:999', 'numeric'],
            'bio' => ['required'],
            'alamat' => ['required']
        ]);

        print_r($request->umur);
        print_r($request->bio);
        print_r($request->alamat);
        
        profile::create([
            'umur' => $request->umur,
            'bio' => $request->bio,
            'alamat' => $request->alamat,
            'user_id' => $user->id
        ]);
        return redirect('profil')->with('success', 'Profil berhasil dibuat');
    }

    public function destroy($id)
    {
        profil::find($id)->delete();
        return redirect()->back()->with('success', 'Profil telah dihapus !!');
    }
}

resources/views/profil/edit.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Update Profile</h1>
            </section>
            <section class="mdc-card__supporting-text">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
                        <form action={{ route('profil.update', $profil->id) }} method="POST">
                            @csrf
                            @method('PUT')
                            <div class="template-demo">
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="umur" class="mdc-text-field__input" name="umur" required value="{{$profil->umur}}">
                                        <label class="mdc-floating-label" for="my-text-field">Umur</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('umur')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="umur" class="mdc-text-field__input" name="bio" required value="{{$profil->bio}}">
                                        <label class="mdc-floating-label" for="my-text-field">Bio</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('bio')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="umur" class="mdc-text-field__input" name="alamat" required value="{{$profil->alamat}}">
                                        <label class="mdc-floating-label" for="my-text-field">Alamat</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('alamat')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>

                                <button type="submit" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                                    Simpan
                                </button>
                                <a href={{ route('kategori.index') }}
                                    class="mdc-button mdc-button--raised secondary-filled-button"
                                    data-mdc-auto-init="MDCRipple">
                                    Kembali
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/profil/index.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Kategori</h1>
                <hr>
                <a href={{ route('profil.edit', $profil->user_id) }} class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                    Update Profile
                </a>
            </section>
            <div>
                <table class="table table-hoverable">
                    <thead>
                        <tr>
                            <th width="20%" class="text-left"><h4>Data</h4></th>
                            <th width="80%" class="text-left"><h4>Profil</h4></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-left">Nama</td><td class="text-left">{{ $profil->user->name }}</td>
                        </tr>
                        <tr>
                            <td class="text-left">Email</td><td class="text-left">{{ $profil->user->email }}</td>
                        </tr>
                        <tr>
                            <td class="text-left">Umur</td><td class="text-left">{{ $profil->umur }}</td>
                        </tr>
                        <tr>
                            <td class="text-left">Bio</td><td class="text-left">{{ $profil->bio }}</td>
                        </tr>
                        <tr>
                            <td class="text-left">Alamat</td><td class="text-left">{{ $profil->alamat }}</td>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/profil/new.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Buat Profile</h1>
            </section>
            <section class="mdc-card__supporting-text">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
                        <form action={{ route('profil.store') }} method="POST">
                            @csrf
                            <div class="template-demo">
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="umur" class="mdc-text-field__input" name="umur">
                                        <label class="mdc-floating-label" for="my-text-field">Umur</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('umur')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="bio" class="mdc-text-field__input" name="bio">
                                        <label class="mdc-floating-label" for="my-text-field">Bio</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('bio')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <div id="demo-tf-box-leading-wrapper">
                                    <div class="mdc-text-field w-100">
                                        <input type="text" id="alamat" class="mdc-text-field__input" name="alamat">
                                        <label class="mdc-floating-label" for="my-text-field">Alamat</label>
                                        <div class="mdc-line-ripple"></div>
                                    </div>
                                    @error('alamat')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>

                                <button type="submit" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                                    Simpan
                                </button>
                                <a href={{ route('kategori.index') }}
                                    class="mdc-button mdc-button--raised secondary-filled-button"
                                    data-mdc-auto-init="MDCRipple">
                                    Kembali
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection