routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TopikController;
use App\Http\Controllers\KomentarController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('kategori', KategoriController::class)->middleware('auth');

Route::resource('profil', ProfilController::class)->middleware('auth');

Route::resource('topik', TopikController::class)->middleware('auth');

Route::resource('komentar', KomentarController::class)->middleware('auth');

Route::get('tinymce', function(){
    return view('tinymce.index');
});

resources/views/partial/navbar.blade.php
<header class="mdc-toolbar mdc-elevation--z4 mdc-toolbar--fixed">
    <div class="mdc-toolbar__row">
        <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
            <a href="#" class="menu-toggler material-icons mdc-toolbar__menu-icon">menu</a>
            <span class="mdc-toolbar__input">
                <div class="mdc-text-field">
                    <input type="text" class="mdc-text-field__input" id="css-only-text-field-box"
                        placeholder="Search anything...">
                </div>
            </span>
        </section>
        <section class="mdc-toolbar__section mdc-toolbar__section--align-end" role="toolbar">
            <div class="mdc-menu-anchor">
            </div>
            <div class="mdc-menu-anchor mr-1">
                <a href="#" class="mdc-toolbar__icon toggle mdc-ripple-surface" data-toggle="dropdown"
                    toggle-dropdown="logout-menu" data-mdc-auto-init="MDCRipple">
                    <i class="material-icons">more_vert</i>
                </a>
                <div class="mdc-simple-menu mdc-simple-menu--right" tabindex="-1" id="logout-menu">
                    <ul class="mdc-simple-menu__items mdc-list" role="menu" aria-hidden="true">
                        {{-- Login --}}
                        @guest
                            <li class="mdc-list-item" role="menuitem" tabindex="0">
                                <a href="/login">
                                    <i class="material-icons mdc-theme--primary mr-1">power_settings_new</i>
                                    Login
                                </a>
                            </li>
                        @endguest

                        {{-- Logout --}}
                        @auth
                            <li class="mdc-list-item" role="menuitem" tabindex="0">
                                <a href="{{ route('profil.index') }}">
                                    <i class="material-icons mdc-theme--primary mr-1">settings</i>
                                    Profile
                                </a>
                            </li>
                            <li class="mdc-list-item" role="menuitem" tabindex="0">
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                    <i class="material-icons mdc-theme--primary mr-1">power_settings_new</i>
                                    Logout
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </li>
                        @endauth
                    </ul>
                </div>
            </div>
        </section>
    </div>
</header>

resources/views/partial/sidebar.blade.php
<aside class="mdc-persistent-drawer mdc-persistent-drawer--open">
    <nav class="mdc-persistent-drawer__drawer">
        <div class="mdc-persistent-drawer__toolbar-spacer">
            <a href="/" class="brand-logo">
                <img src="{{ asset('/template/images/logo.svg') }}" alt="logo">
            </a>
        </div>
        <div class="mdc-list-group">
            <nav class="mdc-list mdc-drawer-menu">
                @auth
                    <div class="mdc-list-item mdc-drawer-item purchase-link">

                        <a href="javascript:void(0)" class="mdc-button mdc-button--raised mdc-button--dense mdc-drawer-link"
                            data-mdc-auto-init="MDCRipple">
                            {{ Auth::user()->name }}
                        </a>
                    </div>
                @endauth
                <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href={{ url('/') }}>
                        <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon"
                            aria-hidden="true">desktop_mac</i>
                        Dashboard
                    </a>
                </div>
                @auth
                    <div class="mdc-list-item mdc-drawer-item">
                        <a class="mdc-drawer-link" href="{{route('topik.index')}}">
                            <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon"
                                aria-hidden="true">question_answer</i>
                            Ajukan Pertanyaan
                        </a>
                    </div>
                    <div class="mdc-list-item mdc-drawer-item" data-toggle="expansionPanel" target-panel="ui-sub-menu">
                        <a class="mdc-drawer-link" href={{ route('kategori.index') }}>
                            <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon"
                                aria-hidden="true">dashboard</i>
                            Kategori
                        </a>
                    </div>
                    <div class="mdc-list-item mdc-drawer-item" data-toggle="expansionPanel" target-panel="ui-sub-menu">
                        <a class="mdc-drawer-link" href='/tinymce'>
                            <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon"
                                aria-hidden="true">event_note</i>
                            Contoh TinyMCE
                        </a>
                    </div>
                    <div class="mdc-list-item mdc-drawer-item" href="#" data-toggle="expansionPanel"
                        target-panel="sample-page-submenu">
                        <div class="mdc-expansion-panel" id="sample-page-submenu">
                            <nav class="mdc-list mdc-drawer-submenu">
                                <div class="mdc-list-item mdc-drawer-item">
                                    <a class="mdc-drawer-link" href="">
                                        Blank Page
                                    </a>
                            </nav>
                        </div>
                    </div>
                @endauth
            </nav>
        </div>
    </nav>
</aside>