routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TopikController;
use App\Http\Controllers\KomentarController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('kategori', KategoriController::class)->middleware('auth');

Route::resource('profil', ProfilController::class)->middleware('auth');

Route::resource('topik', TopikController::class)->middleware('auth');

Route::resource('komentar', KomentarController::class)->middleware('auth');

Route::get('tinymce', function(){
    return view('tinymce.index');
});

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use App\Models\Kategori;

class Kategori extends Model
{
    use HasFactory;
    protected $table = 'kategori';
    protected $guarded = ["id"];

    function topik(){
        return $this->hasMany(Topik::class);
    }
    
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use App\Models\Topik;
use Illuminate\Http\Request;

class KategoriController extends Controller
{

    public function index()
    {
        $kategori = Kategori::all();
        return view('kategori.index', ['data' => $kategori]);
    }


    public function create()
    {
        return view('kategori.new');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => ['required', 'max:255', 'unique:kategori']
        ]);
        Kategori::create([
            'nama' => $request->nama
        ]);

        return redirect('kategori')->with('success', 'Kategori berhasil ditambahkan ...');
    }

    public function edit($id)
    {
        $kategori = Kategori::find($id);
        return view('kategori.edit', [
            'data' => $kategori
        ]);
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => ['required', 'max:255', 'unique:kategori']
        ]);
        Kategori::find($id)->update([
            'nama' => $request->nama
        ]);

        return redirect('kategori')->with('success', 'Kategori berhasil diupdate ...');
    }
    
    public function show($id){
        $kategori = Kategori::find($id);
        $topik = Topik::where('kategori_id', '=', $id)->get();
        return view('kategori.show', compact('topik', 'kategori'));
    }


    public function destroy($id)
    {
        Kategori::find($id)->delete();
        return redirect()->back()->with('success', 'Kategori Berhasil Terhapus !!');
    }

    
}

resources/views/kategori/edit.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Edit Kategori</h1>
            </section>
            <section class="mdc-card__supporting-text">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
                        <form action={{ route('kategori.update', $data['id']) }} method="POST">
                            @csrf
                            @method('PUT')
                            <div class="template-demo">
                                <div id="demo-tf-box-leading-wrapper">
                                    <div id="tf-box-leading-example" class="mdc-text-field mdc-text-field--box w-100">
                                        <input type="text" id="nama" name="nama" class="mdc-text-field__input"
                                            required value="{{ $data['nama'] }}">
                                        <label for="nama" class="mdc-text-field__label">Nama Kategory</label>
                                        <div class="mdc-text-field__bottom-line"></div>
                                    </div>
                                    @error('nama')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <button type="submit" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                                    Update
                                </button>
                                <a href={{ route('kategori.index') }}
                                    class="mdc-button mdc-button--raised secondary-filled-button"
                                    data-mdc-auto-init="MDCRipple">
                                    Kembali
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/kategori/index.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Kategori</h1>
                <hr>
                <a href={{ route('kategori.create') }} class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                    Tambah Kategori
                </a>
            </section>
            <div>
                <table class="table table-hoverable">
                    <thead>
                        <tr>
                            <th width="15%" class="text-left">No</th>
                            <th width="60%" class="text-left">Kategori</th>
                            <th width="25%" class="text-left"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $no = 0;
                        @endphp
                        @forelse ($data as $row)
                            @php
                                $no = $no + 1;
                            @endphp
                            <tr>
                                <td class="text-left">{{ $no }}</td>
                                <td class="text-left"><a href="{{ route('kategori.show', $row->id)}}">{{ $row->nama }}</a></td>
                                <td class="text-left">
                                    <div class="d-flex">
                                        <a class="mdc-button mdc-button--raised" href={{ route('kategori.edit', $row->id) }}
                                            data-mdc-auto-init="MDCRipple">Edit</a>
                                        <form class="pl-1" action={{ route('kategori.destroy', $row->id) }}
                                            method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $row->id }}">
                                            <button class="mdc-button mdc-button--raised secondary-filled-button"
                                                type="submit" data-mdc-auto-init="MDCRipple">Hapus</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center">Data kosong</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/kategori/new.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Tambah Kategori</h1>
            </section>
            <section class="mdc-card__supporting-text">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
                        <form action={{ route('kategori.store') }} method="POST">
                            @csrf
                            <div class="template-demo">
                                <div id="demo-tf-box-leading-wrapper">
                                    <div id="tf-box-leading-example" class="mdc-text-field mdc-text-field--box w-100">
                                        <input type="text" id="nama" name="nama" class="mdc-text-field__input"
                                            required value="{{ old('nama') }}">
                                        <label for="nama" class="mdc-text-field__label">Nama Kategory</label>
                                        <div class="mdc-text-field__bottom-line"></div>
                                    </div>
                                    @error('nama')
                                        <p>
                                            {{ $message }}
                                        </p>
                                    @enderror
                                </div>
                                <button type="submit" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple">
                                    Simpan
                                </button>
                                <a href={{ route('kategori.index') }}
                                    class="mdc-button mdc-button--raised secondary-filled-button"
                                    data-mdc-auto-init="MDCRipple">
                                    Kembali
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/kategori/show.blade.php
@extends('layouts.template')
@section('content')
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
            <section class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">Kategori {{ $kategori->nama }}</h1>
                <hr>
                
            </section>
            <div>
                <table class="table table-hoverable">
                    <thead>
                        <tr>
                            <th width="15%" class="text-left">No</th>
                            <th width="60%" class="text-left">Judul</th>
                            <th width="25%" class="text-left"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $no = 0;
                            $public_folder = public_path();
                        @endphp
                        @forelse ($topik as $row)
                            @php
                                $no = $no + 1;
                            @endphp
                            <tr>
                                <td class="text-left">{{ $no }}</td>
                                <td class="text-left"><a href="{{ route('topik.show', $row->id)}}">{{ $row->judul }}</a></td>
                                <td class="text-left">
                                    <div class="d-flex">
                                        @if ($row->user->id == Auth::user()->id)
                                        <a class="mdc-button mdc-button--raised" href={{ route('topik.edit', $row->id) }}
                                            data-mdc-auto-init="MDCRipple">Edit</a>
                                        <form class="pl-1" action={{ route('topik.destroy', $row->id) }}
                                            method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input type="hidden" name="id" value="{{ $row->id }}">
                                            <button class="mdc-button mdc-button--raised secondary-filled-button"
                                                type="submit" data-mdc-auto-init="MDCRipple">Hapus</button>
                                        </form>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="text-left"><img src="{{ asset('image/'.$row->gambar)}}" height="100"></td>
                                <td class="text-left">{{ $row->pertanyaan }}</td>
                                @php
                                @endphp
                                <td class="text-left"></td> 
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-left">Data kosong</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection